### ISSUE TITLE
Click and Release doesn't work for drawing on IE11

### ISSUE THREAD

**Issue by rajadain** [azavea/idb-osm-extraction-tool#24]
In Chrome, after selecting Box Drawing, one can either click and drag a box, or click to start and click again to end drawing the box.

On IE11, each click starts a new box, that never finishes drawing:

![2018-08-01 16 04 17](https://user-images.githubusercontent.com/1430060/43545763-c4121c20-95a4-11e8-8ad8-9fe3530f07ec.gif)

Click and drag works correctly.

**Comment by rajadain** [comment]
This problem also exists in the main Leaflet.Draw demo: https://leaflet.github.io/Leaflet.draw/docs/examples/full.html. Maybe it is out of scope of this project.

**Comment by kellyi** [comment]
Yeah, just saw that. I'm going to rapidly try to just disable the rectangle draw tool on mouseup if it's active in IE11.

FWIW the instructions for the rectangle tool say "click and drag", so I think the actual bug is that Leaflet Draw also allows the rectangle tool to have the "click two points" behavior:

![screen shot 2018-08-02 at 11 10 47 am](https://user-images.githubusercontent.com/4165523/43593027-d7cdcf70-9644-11e8-83f5-d237d5229030.png)
